# Generated by Django 4.1.6 on 2023-03-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
